### ISSUE TITLE
Feature request: auto-refresh UI if file has been changed by external process

### ISSUE THREAD

**Issue by ElderOrb** [fuchsmich/zutun.txt#1]
Is it possible to add refreshing UI on txt file changes? Asking because I've shared todo file using syncthing, so now I have synchronized todo list on all my devices. But the issue is that it is a bit inconvenient that every time I make changes on PC I have to close/open ZuTun on Jolla to get actual task list.

**Comment by fuchsmich** [comment]
Hi,

this should happen every time the main window or cover gets focus.
I will check this. Do you have the latest version from openrepos installed?

Am 20.03.2017 um 13:29 schrieb elderorb:

**Comment by ElderOrb** [comment]
It turned out I wasn't using the latest version and after updating seems like it really works! Thank you!

**Comment by fuchsmich** [comment]
Great. Thanks for your comment anyway.

Am 20.03.2017 um 14:09 schrieb elderorb:
