### ISSUE TITLE
[Feature Request] Allow rotation of masks

### ISSUE THREAD

**Issue by sphenotux** [fuchsmich/zutun.txt#12]
As of now, user has to go forth-and-back. Enable continous step-through.
_Tasks - Project filter - Context filter - Tasks_... User always wipes only in **one** direction, e.g. to the right (or to the left), and comes out again at the origin. The "clock" from _Jolla_ does this with alarm, timer, stopwatch.

**Comment by fuchsmich** [comment]
Just a hint: you can attach the project-filter to the left of the tasklist (via settings).

**Comment by sphenotux** [comment]
Yes, I have foundt that option helpful, setting is already in use. Quicker for me to go left and right. Thx anyhow.
I would like to rate **this** request _low prio_. Nice-2-have, but can live without.

**Comment by fuchsmich** [comment]
I put all filters on one page now.
