### ISSUE TITLE
[Feature Request] Filter: Allow multiple filters per project/context

### ISSUE THREAD

**Issue by sphenotux** [fuchsmich/zutun.txt#13]
Currently only 1 keyword is selectable.
I just love to put private + professional things into a **single** file/list, and then there will be quite a lot of projects/contexts, with housework, shopping, gardening, work... Sometimes it is a good idea to select 2 or more projects/contexts at a time.
EDIT
What I meant is:
Ability to store **multiple** documents, e.g. todo-work.txt and todo-home.txt (for 3?) files - or - history for the last (3?) files used

**Comment by fuchsmich** [comment]
Yes filters are implemented very poorly. There should be more options.

I'm thinking about:
1) more possibilities to combine filters
2) invert filters
3) filter for custom strings
4) save views as custom filters

**Comment by sphenotux** [comment]
EDIT
... 1. Yes, enable to pick **multiple** projects/contexts in one single rush (as of now, user has to go back to _Tasks_ view and forth to the _filter_ again)
/EDIT
... 5. Filter by priority A, B, C... (and sort)

**Comment by fuchsmich** [comment]
There is a more advanced filter choice now.

Filters combine with logic "and" by default (like it was before), but you can additionally choose to combine with "or" and/or "not".
