### ISSUE TITLE
[Feature Request] Filter: Reset filter

### ISSUE THREAD

**Issue by sphenotux** [fuchsmich/zutun.txt#15]
_(Low prio, as there is a workaround, see below. Just an idea to make the App even more comfortable for non-experienced users (like I am, as of now ;-).)_

Had an issue in v1.7.2-2 and SF OS 3.1.0.11. Maybe the place where I stumbled can be caught elegantly? If the **last** task containing a context/project is deleted, automatically reset (all?) filters? On the other hand: It stands on the mask for the _Tasks_. Those who are able to read <> I will get along. So rather a _nice-2-have_ than a _must-have_.

Current workaround for the **user**: a) User must filter settings carefully in _Task_ view and b) User must clear **all** project/context/... filters from time to time.

**Comment by fuchsmich** [comment]
Generally speaking in todo.txt (as I understand it) you usually don't delete tasks, you mark them as done (and later on move them to archive.txt (which isn't implemented in my app)).

How I understand the issue:
1) A filter item should be removed from settings, if it's not applicable anymore.

2) There should be a hint, if all tasks are filtered out.

**Comment by sphenotux** [comment]
Yes, you mark them as DONE. In plain text, by a lower case lettre x at the very beginning of a line (task). This is exactly what your todo.txt file looks like in a text editor. ZuTun.txt displays them by crossed out font - what I personally like -, other GUIs use a light font, like grey instead of black.

As I use _SyncThing_ (and _SyncDings_), I have the capability to use a **real** keyboard instead of a touch screen etc. to edit the plain text file. Nice workaround. IMHO done.txt/archive.txt native out of _ZuTun.txt_ is nice-2-have, but **not** critical.
(Found _done.txt_ in e.g. _jdotxt_ and other GUIs instead of _archive.txt_.)

Off-Topic ends here, sry 4 that. Back to the _Reset filter_ issue:
1. Yes
2. Yes

This happens to me when changing the _todo.txt_ file in use. I already got used to filter reset.

But I guess acceptance of _ZuTun.txt_ by (newbie) users may rise if hints are given.

**Comment by fuchsmich** [comment]
Hint is implemented, but maybe there should be a easier accessible button for clearing filters.
