### ISSUE TITLE
[Feature Request] Delete tasks: enable remorse timer

### ISSUE THREAD

**Issue by sphenotux** [fuchsmich/zutun.txt#16]
Make the timer for deleting editable, e.g. via _Settings_
Currently fixed to 5 seconds. Sometimes feels quite long. Would like to set this to 2 or 3 seconds instead.

(E.g. the _TaskList_ of Thomas Amler (GitHub) aka _Armadillo_ allows this. I find it sexy. However, I quit using _TaskList_ for the sake of _ZuTun_ ;-).)

**Comment by fuchsmich** [comment]
This is set to 3sec now.
