### ISSUE TITLE
[Feature Request] Delete: Select several tasks and delete them as a package

### ISSUE THREAD

**Issue by sphenotux** [fuchsmich/zutun.txt#17]
_(Low prio)_
As of now (v1.7.2-2), deletion is possible for **one** single task only + wait for 5 seconds (timer).
See # 16

Alternative title here: Delete several tasks one after the other. Pick task1 for deletion, timer1 starts. Pick task2 for deletion immediately (while timer1 is still running), timer2 starts etc.

At the moment you have to wait until the deletion of the **first** task selected for deletion has been completed, otherwise nothing else will be deleted. (OK, guess, because everything is in a ._txt_-file, would that be **multiple** access to a single file, and therefore impossible?

_TaskList_ uses IMHO a database, of course working on multiple tasks simultaneously works there.

**Comment by fuchsmich** [comment]
Should work now. Please test.
