### ISSUE TITLE
bug or featur request, if todo.txt path is change the App should jump to the current one

### ISSUE THREAD

**Issue by berndhahnebach** [fuchsmich/zutun.txt#18]
Started to use zutun.txt and Notzen.md some weeks ago. Both are very very useful! I really appreciate any developemnt in the regard of these text formats.

I use the todo.txt on multiple todo files. I just change the path to the todo in the preferences. On touch of the button choose file (in German "Datei wählen") the app does not jump to the current file but to the root directory instead. If this pref is set I would expect the pref to jumt to the current file. Changing to another file in the same directory than only would be just one touch instead of browsing to the path again from root directory.

cheers bernd

**Comment by fuchsmich** [comment]
Makes sense.

**Comment by sphenotux** [comment]
Please see discussion on #13 as well. Multiple files/history/radio buttons.

One up.

**Comment by fuchsmich** [comment]
I couldn't find a easy way to open the filebrowser in a specific path, except writing a new one, which I'm not keen on.

But some kind of history or recent files should be doable.

**Comment by sphenotux** [comment]
My thought was much more simple: call _read_ in _fileio_ with the _settings.todoTxtLocation_ from _Settings.qml_? This should be the last known _todo.txt_ file location.

**Comment by fuchsmich** [comment]
When you choose a file and leave the settings page, the path is [stored in settings](https://github.com/fuchsmich/zutun.txt/blob/86bd79d6d9ddd942a94479e6e0333c30ce80cf37/qml/pages/SettingsPage.qml#L116). There is no old path left over anywhere.

**Comment by fuchsmich** [comment]
There's a list of recent files now. 
  - the list stores 3 last paths
  - when you leave settings, path is stored if not already in the list.
  - you remove a path manually
  - you can pin/unpin paths
