### ISSUE TITLE
how to compile and run the app from source ?

### ISSUE THREAD

**Issue by berndhahnebach** [fuchsmich/zutun.txt#19]
No really an issue. It is years ago I did do some development for mobile hardware (was on the best phone ever in history, on a Nokia N9).

I may would like to give it a try on Sailfish. Actually I would like to start with one of your apps. On a Linux desktop I regullarly do software development for https://github.com/FreeCAD/FreeCAD But actually I have no idea how to start on a mobile plattform like sailfish. Do you have any informations how to get started to compile and run your apps from source ?

**Comment by fuchsmich** [comment]
1) The SDK is very easy to use on Linux  and Windows https://sailfishos.org/wiki/Application_Development
Just download and install it. Make sure VirtualBox is working on your dev-machine before.

2) Most of my apps don't need to be compiled. The code is qml and some python code. But anyways it's most convenient to install the SDK and use it for deployment (copy the files to phone or emulator).

3) Then you maybe should start to learn about qml and if you want to use c++ about the data exchange between c++/qml.

**Comment by sphenotux** [comment]
Interested as well. Got _VirtualBox_ and SDK _Sailfish.IDE_ running. Pulled source code of _ZuTun.txt_ via git.
_(Got some error messages when pressing play in SDK; my prob)_

Should the emulator of 3.1.0.11 or 3.1.0.12 display a button for _ZuTun.txt_ in VirtualBox?
_(I dare **not** send a pull request without having run the app at least once in my try-and-error setup ;-).)_

EDIT I would very much appreciate some help. _Maybe this is a Newbie question..._
The last set of lines of the error messages I get when running ...3.0.12 Release Deploy RPM. Partly in German:
>...
> + install -d /home/deploy/installroot/usr/share/lipstick/quickactions
> + install /home/mersdk/share/Dokumente/build-harbour-zutun-SailfishOS_3_1_0_12_i486_in_Sailfish_OS_Build_Engine-Release/../zutun.txt/quickaction.conf /home/deploy/installroot/usr/share/lipstick/quickactions/info.fuxl.zutuntxt.conf
install: cannot stat `/home/mersdk/share/Dokumente/build-harbour-zutun-SailfishOS_3_1_0_12_i486_in_Sailfish_OS_Build_Engine-Release/../zutun.txt/quickaction.conf': No such file or directory

> RPM build errors:
> error: Bad exit status from /var/tmp/rpm-tmp.4Ltj3l (%install)
    Bad exit status from /var/tmp/rpm-tmp.4Ltj3l (%install)
21:07:05: Der Prozess "/home/frederik/.config/SailfishOS-SDK/mer-sdk-tools/Sailfish OS Build Engine/SailfishOS-3.1.0.12-i486/deploy" wurde mit dem Rückgabewert 1 beendet.
Fehler beim Erstellen/Deployment des Projekts harbour-zutun (Kit: SailfishOS-3.1.0.12-i486 (in Sailfish OS Build Engine))
Bei der Ausführung von Schritt "RPM"
21:07:05: Verstrichene Zeit: 00:19.

**Comment by fuchsmich** [comment]
Ah, yes. Back then I didn't know how to install files, which are not found automatically by the SDK.

Checkout the devel branch.

But wait with PRs till next version, because there are **a lot** of changes in the branch smoothlist, which hopefully work soon.

**Comment by sphenotux** [comment]
Great, looking forward to the next version ;-).

Anyhow, I would like to join/contribute. Again, Newbie question/screenshot. All I need is a little nudge (I hope).
![devel](https://user-images.githubusercontent.com/55288702/65179134-7d8fd200-da5a-11e9-902b-24cfafe368c6.png)

**Comment by berndhahnebach** [comment]
> , because there are **a lot** of changes in the branch smoothlist, which hopefully work soon.

wow cool and thanks for the links ...

**Comment by fuchsmich** [comment]
> Anyhow, I would like to join/contribute. Again, Newbie question/screenshot. All I need is a little nudge (I hope).

Sure, you should. Select the deployment method "Deploy As RPM Package" for i486 and hit "Run" (= green triangle (arrow)).

![Screenshot_20190919_183002](https://user-images.githubusercontent.com/2899761/65263020-e4b98f00-db0b-11e9-9de3-e95d6bc28f61.png)

**Comment by sphenotux** [comment]
Sry 2 disturb again. Got setup exactly like in your screenshot above. Identical picture in the 3.1.0.12 emulator. No errors so far - but unfortunately no _ZuTun.txt_ icon, either.

Do I have to copy some files manually?

**Comment by fuchsmich** [comment]
Hm, strange. What if you create a new Project. File -> New Project -> Application -> Sailfish OS... (QML only) and then confirm everything and deploy it the same way.

**Comment by sphenotux** [comment]
_Took me some time to get back here... Finally arrived ;-)._

SF OS Emulator starts in 3.1.0.12. Looks like **my** image above. Just _Components_ and _Settings_. No surprise a **blank** project lacks of _zutun.txt_. But hey, what else can I do?

**Comment by fuchsmich** [comment]
Does this help?

https://sailfishos.org/wiki/Application_SDK_Your_First_App#Build_and_Deploy_the_App

**Comment by sphenotux** [comment]
Good news: Got _zutun.txt_ running via _Qt Creator_ by luck yesterday night.
- Commented out _zutun.txt/rpm/harbour-zutun.spec_ lines 63+65+80+81.
- In addition, added a shared folder in the VM.

Bad news: unable to reproduce **now**.
Could you please check if project / VM image contains all required files? Thx.

**Comment by sphenotux** [comment]
Update:
Different machine. SF OS IDE aka Qt Creator installed from scratch. virtualbox-qt added on my LinuxMint Desktop. 
Devel branch pulled from here. Opened as project in 3....12 as debug/rpm.
Voilà: zutun.txt running.

Now looking forward to the update.

Will work on permanent zutun.txt.in VM next. Go, go, go :-)!

_EDIT 2019-10-28 21:45: Started IDE again on my "older" machine. Got zutun.txt running there as well. /EDIT_

**Comment by sphenotux** [comment]
... in addition: lines mentioned above commented out #.
(SF OS native browser does not allow editing comments, so I post a new one.)
