### ISSUE TITLE
[Feature Request] Add counter for (total number of) tasks at top of Task view

### ISSUE THREAD

**Issue by sphenotux** [fuchsmich/zutun.txt#21]
Similar to _Context_ and _Project_ view, which show _open_ and _done_ tasks (e.g. (2/3), meaning "two open of three in total")), the _Task view_ should show the total number of (open) tasks.
At the top of the GUI, on the left - opposite to the filters?
Informative counter - nice 2 have.
[Edit: Writing this in order to clean up my zutun.txt - todo.txt file ;-). /Edit]

**Comment by fuchsmich** [comment]
The counter in the Filterpages actually show (visible/total). If you select a filter the count changes. I don't know if this is usefull at all.
Maybe your suggestion (open/total) would be better?

**Comment by sphenotux** [comment]
Hm... not sure about Filterpages, either. Options:
- Discard at all or
- Make available as option in _Settings_, aka _(Show/) Hide number of items_? How much work would that mean, and how many users would appreciate that?

IMHO a counter for the number of **visible** lines in the _Task_ view (main page) is sufficient and helpful for everyone.
Again, just a **suggestion**: _Task_ view shows counter by default, but may be set to "invisible" or similar by user in _Settings_?

EDIT: If **unfiltered**, it would just mean to count the lines **not** starting with a lower-case "x", right? As of now, I am not skilled enough to handle this (alone). In _Bash_, one would probably use the _grep -c_ command...

**Comment by fuchsmich** [comment]
I guess we should have a counter in the main taskview (NumberOfVisible/TotalNumber). Implementing this is a oneliner.
