### ISSUE TITLE
[Question] How many elements does SF OS show in 'Events' view?

### ISSUE THREAD

**Issue by sphenotux** [fuchsmich/zutun.txt#22]
When _zutun.txt_ is up and running, the '_Events_' view in SF OS 3.x shows a list of _due_ elements in **descending** order.

Where, as a user, can I a) change the order e.g. to **ascending** and/or b) adjust the **number** of items shown in '_Events_' view?

(Honestly, I was very happy to find any hint in _Events_ view at all. Now, after the duty comes the cure.)

**Comment by fuchsmich** [comment]
Notifications are just a very quick hack still. Nothing to configure yet.

**Comment by sphenotux** [comment]
Fine for me. Just wanted to be sure not to have missed something. Thx and closed.
