### ISSUE TITLE
add completion date on completion

### ISSUE THREAD

**Issue by fuchsmich** [fuchsmich/zutun.txt#26]
https://openrepos.net/comment/32163#comment-32163

**Comment by fuchsmich** [comment]
The [specification](https://github.com/todotxt/todo.txt) is not clear about how the completion date has to be interpreted, which is also mentioned in this [issue](https://github.com/todotxt/todo.txt/issues/26).

So I will implement it like this:

`2020-01-01 do sth` task was created on 01.01.2020
`x 2020-01-15 did sth` task was completed on 15.01.2020
`x 2020-01-15 2020-01-01 did sth else` task was created on 01.01.2020 and completed on 15.01.2020

The second line is interpreted differently now, this will change in future releases.

**Comment by sphenotux** [comment]
I fully agree with your suggestion.
Completion date should always be added automatically when a task is closed.
If user did NOT provide a creation date, one single date in a closed task is the completion date.
One could think about additional settings:
* Allow creation date to ALWAYS be added to new tasks automatically.
* Toggle visibility of creation date in (open?) tasks

**Comment by fuchsmich** [comment]
> Allow creation date to ALWAYS be added to new tasks automatically.

This is definitely on my todo.txt list.

> Toggle visibility of creation date in (open?) tasks

You mean inside settings? ( #30 )

**Comment by sphenotux** [comment]
Glad to read.
Yes. E.g. I am using 'Simpletask' on my Android phone at work. Checkbox in settings says (in German): 'Zeitstempel für neue Aufgaben - [subtitle] Erstellungsdatum automatisch hinzufügen'.

**Comment by sphenotux** [comment]
... in addition: If 'Add timestamp for new tasks' is chosen in Settings, the tasklist shows the tasks without creation date. Better overview, shorter list/tasks.
When editing a task = detailed view, creation date is shown.

**Comment by fuchsmich** [comment]
My comment was confusing, it was meant like this:

> Allow creation date to ALWAYS be added to new tasks automatically.

This is definitely on my todo.txt list.  ( #30 )

> Toggle visibility of creation date in (open?) tasks

You mean inside settings?

**Comment by sphenotux** [comment]
Yes, inside settings.

In addition, as of now in v1.7.2-2, _completion_ date is added **only** if _creation_ date was added by the user. If **no** _creation_ date was given, **no** _completion_ date is added.

**Comment by fuchsmich** [comment]
Should be solved with new release.
