### ISSUE TITLE
[Minor improvement] Clean multiple whitespaces when saving

### ISSUE THREAD

**Issue by sphenotux** [fuchsmich/zutun.txt#31]
**Display** of tasks in **tasklist** is OK: seems to contain single whitespaces only
while
Real content of a task when editing/adding a single task is not: single tasks allow multiple (> 1) whitespaces between words, or before/after +project or @context tags

Not REALLY an issue; may be interesting for text editor enthusiasts.

**Comment by sphenotux** [comment]
DONE with a RegEx. Sent PR. If OK, this one can be closed.

Edit: Added _TaskLiskItem.qml_ by error in ccdf64d. Corrected by 01a31dc. Long story short, **one** file is affected only: _TaskEditPage.qml_

**Comment by fuchsmich** [comment]
Thanks. Is there some specification about having multiple whitespaces insie a task?

**Comment by sphenotux** [comment]
Welcome. I don't think there is any spec at all. Multiple whitespaces IMHO just don't make sense, no need for that. Some text tools might count characters wrong.

**Comment by fuchsmich** [comment]
I find nothing wrong with removing multiple whitespaces, just wanted to ask, will integrate it.
